<?php
# This file was automatically generated by the MediaWiki 1.41.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "DUWIKI";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://duwiki.100won.duckdns.org";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/my_logo.png",
	'icon' => "$wgResourceBasePath/resources/assets/my_logo.png",
];
$wgFavicon = "$wgResourceBasePath/resources/assets/my_favicon.png";
## Liberty 아이콘 관련
$wgLibertyNavBarLogoImage = "$wgResourceBasePath/resources/assets/my_logo.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgFileExtensions = [
	    'png', 'gif', 'jpg', 'jpeg', 'doc', 'xls', 'pdf', 'mp3', 'ogg', 'zip', 'txt',
	        // 필요에 따라 추가적인 파일 형식을 포함할 수 있습니다.
];

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "ko";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "3ccc0ea41e8b372536de04bfa8b1a98b91dd082f3a667e51e298b1c15218b18b";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "fee5ad4a121a5880";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "liberty";


# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );
wfLoadSkin( 'Liberty' );

# End of automatically generated settings.
# Add more configuration options below.


## Liberty settings
#Set color 
$wgLibertyMainColor = '#008000';
$wgLibertySecondColor = '#ece6cc';

## wiki editor
wfLoadExtension( 'WikiEditor' );
$wgHiddenPrefs[] = 'usebetatoolbar';
$wgWikiEditorRealtimePreview = true;

## ogtag
$wgHooks['BeforePageDisplay'][] = function ( $out, $skin ) {
    $title = 'DUWIKI';
    $url = 'https://duwiki.100won.duckdns.org/index.php/대문';
    $description = '모두가 함께하는 DUWIKI 입니다.';
    $logo = 'https://duwiki.100won.duckdns.org/images/d/da/Ogtag.png';
    $out->addHeadItem(
        'og:title',
        "<meta property=\"og:title\" content=\"$title\" />"
    );
    $out->addHeadItem(
        'og:url',
        "<meta property=\"og:url\" content=\"$url\" />"
    );
    $out->addHeadItem(
        'og:description',
        "<meta property=\"og:description\" content=\"$description\" />"
    );
    $out->addHeadItem(
        'og:type',
        '<meta property="og:type" content="website" />'
    );
    $out->addHeadItem(
        'og:image',
        "<meta property=\"og:image\" content=\"" . htmlspecialchars($logo) . "\" />"
    );
    return true;
};
